### ISSUE TITLE
App bar appears transparent when no theme applied

### ISSUE THREAD

**Issue by KyNorthstar** [BlueHuskyStudios/stylesheets#22]
There should be a reasonable backup color, like this:

```scss
.app-bar {
    background-color: var(--theme-primary-color, var(--theme-background-color-at-level-raised));
}
```
