### ISSUE TITLE
Introduce equal-item-sizing to flex

### ISSUE THREAD

**Issue by KyNorthstar** [BlueHuskyStudios/stylesheets#24]
Something like this, in `flex-incl.scss`:

```scss
@mixin flex-sizes-equal() {
    flex-basis: 0;
    flex-grow: 1;
    flex-shrink: 0;
}
```
```scss
.flex-row.flex-horiz-sizes-equal>*,
.flex-column.flex-vert-sizes-equal>* {
    @include flex-sizes-equal();
}
```
