### ISSUE TITLE
Pull down `main` element when on a large smartphone

### ISSUE THREAD

**Issue by KyNorthstar** [BlueHuskyStudios/stylesheets#26]
Inspired by Samsung's decisions in making OneUI, this will help the interactive content be easier to reach one-handed.

```css
main {
  transition-property: padding-top;
}


@media screen
  and (max-width: 5in)
  and (min-height: 6in)
  and (max-aspect-ratio: 10/16)
  and (min-aspect-ratio: 7/16)
{
  main {
    padding-top: 30vh;
  }
}
```
