### ISSUE TITLE
Font Icons have improper width

### ISSUE THREAD

**Issue by KyNorthstar** [BlueHuskyStudios/stylesheets#40]
Not sure how/why this was added, but this rule causes font icons to be incorrectly placed:

```scss
@import "material-buttons";
@import "icons-import";



#{$button-selector} {
    #{$icon-selector} {
        width: 2ex;
    }
}
```
